# Generated by Django 5.0 on 2023-12-07 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_certificado', models.CharField(max_length=255, verbose_name='nombre del certificado')),
                ('fecha_certificado', models.DateField(verbose_name='fecha realizado')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_last_name', models.CharField(max_length=255, verbose_name='apellido paterno')),
                ('second_last_name', models.CharField(max_length=255, verbose_name='apellido materno')),
                ('name', models.CharField(max_length=255, verbose_name='primer nombre')),
                ('employee_rut', models.CharField(max_length=255, verbose_name='rut empleado')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 's',
            },
        ),
        migrations.CreateModel(
            name='certificateUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_realizacion', models.DateField(verbose_name='fecha realizacion')),
                ('certificado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultasmetso.certificados')),
                ('usuarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultasmetso.usuarios')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 's',
            },
        ),
    ]
