# Generated by Django 5.0 on 2023-12-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultasmetso', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificados',
            options={'verbose_name': '', 'verbose_name_plural': 'certificados'},
        ),
        migrations.AlterModelOptions(
            name='certificateusers',
            options={'verbose_name': '', 'verbose_name_plural': 'Información del empleado'},
        ),
        migrations.AlterModelOptions(
            name='usuarios',
            options={'verbose_name': '', 'verbose_name_plural': 'usuarios'},
        ),
        migrations.AlterField(
            model_name='certificados',
            name='fecha_certificado',
            field=models.DateField(verbose_name='fecha agregado al sistema'),
        ),
        migrations.AlterField(
            model_name='certificateusers',
            name='fecha_realizacion',
            field=models.DateField(verbose_name='fecha vencimiento'),
        ),
    ]
