# Generated by Django 5.0 on 2023-12-27 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultasmetso', '0002_alter_certificados_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificateusers',
            name='fecha_realizacion',
            field=models.DateTimeField(verbose_name='fecha vencimiento'),
        ),
    ]
