# Generated by Django 5.0 on 2023-12-27 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultasmetso', '0003_alter_certificateusers_fecha_realizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificateusers',
            name='fecha_realizacion',
            field=models.DateField(verbose_name='fecha vencimiento'),
        ),
    ]
