# Generated by Django 5.0.1 on 2024-01-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultasmetso', '0004_alter_certificateusers_fecha_realizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificateusers',
            name='fecha_realizacion',
            field=models.DateField(null=True, verbose_name='fecha vencimiento'),
        ),
    ]
