# Generated by Django 5.0.1 on 2024-01-03 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultasmetso', '0006_alter_certificateusers_fecha_realizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='cargo',
            field=models.CharField(default='no definido', max_length=255, verbose_name='cargo del empleado'),
        ),
    ]
