# Generated by Django 5.0.1 on 2024-01-04 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultasmetso', '0008_alter_usuarios_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='contrato',
            field=models.CharField(choices=[('base', 'Base'), ('spot', 'Spot')], default='', max_length=10, verbose_name='cargo del empleado'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='cargo',
            field=models.CharField(default='no definido', max_length=255, verbose_name='cargo del empleado'),
        ),
    ]
